#pragma once
#include "SDK/CEntity.h"
#include <map>
#include <vector>




const std::vector<std::pair<int, const char*>> bayonet_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},
{410,"Damascus Steel"},
{558,"Lore"},
{563,"Black Laminate"},
{573,"Autotronic"},
{578,"Bright water"},
{580,"Freehand"}
};
extern const std::vector<std::pair<int, const char*>> bayonet_skins;


const std::vector<std::pair<int, const char*>> m9bayonet_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},
{410,"Damascus Steel"},
{562,"Lore"},
{567,"Black Laminate"},
{577,"Autotronic"},
{579,"Bright water"},
{582,"Freehand"}
};
extern const std::vector<std::pair<int, const char*>> m9bayonet_skins;



const std::vector<std::pair<int, const char*>> bowie_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> bowie_skins;

const std::vector<std::pair<int, const char*>> butterfly_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> butterfly_skins;

const std::vector<std::pair<int, const char*>> push_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> push_skins;


const std::vector<std::pair<int, const char*>> falchion_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> falchion_skins;

const std::vector<std::pair<int, const char*>> flip_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},
{410,"Damascus Steel"},
{559,"Lore"},
{564,"Black Laminate"},
{574,"Autotronic"},
{578,"Bright water"},
{580,"Freehand"}
};
extern const std::vector<std::pair<int, const char*>> flip_skins;


const std::vector<std::pair<int, const char*>> gut_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},
{410,"Damascus Steel"},
{560,"Lore"},
{565,"Black Laminate"},
{575,"Autotronic"},
{578,"Bright water"},
{580,"Freehand"}
};
extern const std::vector<std::pair<int, const char*>> gut_skins;

const std::vector<std::pair<int, const char*>> tatical_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> tatical_skins;

const std::vector<std::pair<int, const char*>> karambit_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},
{410,"Damascus Steel"},
{561,"Lore"},
{566,"Black Laminate"},
{576,"Autotronic"},
{578,"Bright water"},
{582,"Freehand"}
};
extern const std::vector<std::pair<int, const char*>> karambit_skins;

const std::vector<std::pair<int, const char*>> jack_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> jack_skins;

const std::vector<std::pair<int, const char*>> classic_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> classic_skins;


const std::vector<std::pair<int, const char*>> stiletto_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> stiletto_skins;


const std::vector<std::pair<int, const char*>> ursus_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> ursus_skins;

const std::vector<std::pair<int, const char*>> widowmaker_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> widowmaker_skins;

const std::vector<std::pair<int, const char*>> skeleton_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> skeleton_skins;


const std::vector<std::pair<int, const char*>> outdoor_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> outdoor_skins;


const std::vector<std::pair<int, const char*>> canis_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> canis_skins;

const std::vector<std::pair<int, const char*>> cord_skins =
{
    {5,"Forest DDPAT"},
{12,"Crimson Web"},
{38,"Fade"},
{40,"Night"},
{42,"Blue Steel"},
{43,"Stained"},
{44,"Case Hardened"},
{59,"Slaughter"},
{72,"Safari Mesh"},
{77,"Boreal Forest"},
{98,"Ultraviolet"},
{143,"Urban Masked"},
{175,"Scorched"},
{409,"Tiger Tooth"},
{413,"Marble Fade"},
{414,"Rust Coat"},
{415,"Doppler RED"},
{416,"Doppler BLUE"},
{417,"Doppler BLACK PEARL"},
{418,"Doppler PHASE 1"},
{419,"Doppler PHASE 2"},
{420,"Doppler PHASE 3"},
{421,"Doppler PHASE 4"},
{568,"Gamma Doppler EMERALD"},
{569,"Gamma Doppler PHASE 1"},
{570,"Gamma Doppler PHASE 2"},
{571,"Gamma Doppler PHASE 3"},
{572,"Gamma Doppler PHASE 4"},

};
extern const std::vector<std::pair<int, const char*>> cord_skins;

const std::vector<std::pair<int, const char*>> guns =
{
   { (int)ItemDefinitionIndex::WEAPON_AK47,			"AK-47" },
{ (int)ItemDefinitionIndex::WEAPON_AUG,			"AUG" },
{ (int)ItemDefinitionIndex::WEAPON_AWP,			"AWP" },
{ (int)ItemDefinitionIndex::WEAPON_CZ75,			"CZ75-A" },
{ (int)ItemDefinitionIndex::WEAPON_DEAGLE,		"Desert Eagle" },
{ (int)ItemDefinitionIndex::WEAPON_ELITE,			"Dual Barettas" },
{ (int)ItemDefinitionIndex::WEAPON_FAMAS,			"Famas" },
{ (int)ItemDefinitionIndex::WEAPON_FIVESEVEN, 	"Five-Seven" },
{ (int)ItemDefinitionIndex::WEAPON_GALIL,		"Galil-AR" },
{ (int)ItemDefinitionIndex::WEAPON_G3SG1,			"G3SG1" },
{ (int)ItemDefinitionIndex::WEAPON_GLOCK,			"Glock-18" },
{ (int)ItemDefinitionIndex::WEAPON_M249,			"M249" },
{ (int)ItemDefinitionIndex::WEAPON_M4A1S, "M4A1-S" },
{ (int)ItemDefinitionIndex::WEAPON_M4A4,			"M4A4" },
{ (int)ItemDefinitionIndex::WEAPON_MAC10,			"MAC-10" },
{ (int)ItemDefinitionIndex::WEAPON_MAG7,			"Mag-7" },
{ (int)ItemDefinitionIndex::WEAPON_MP7,			"MP7" },
{ (int)ItemDefinitionIndex::WEAPON_MP5SD,		"MP5-SD" },
{ (int)ItemDefinitionIndex::WEAPON_MP9,			"MP9" },
{ (int)ItemDefinitionIndex::WEAPON_NEGEV,			"Negev" },
{ (int)ItemDefinitionIndex::WEAPON_NOVA,			"Nova" },
{ (int)ItemDefinitionIndex::WEAPON_P2000,		"P2000" },
{ (int)ItemDefinitionIndex::WEAPON_P250,			"P250" },
{ (int)ItemDefinitionIndex::WEAPON_P90,			"P90" },
{ (int)ItemDefinitionIndex::WEAPON_BIZON,			"PP-Bizon" },
{ (int)ItemDefinitionIndex::WEAPON_REVOLVER,		"R8 Revolver" },
{ (int)ItemDefinitionIndex::WEAPON_SAWEDOFF,		"Sawed-Off" },
{ (int)ItemDefinitionIndex::WEAPON_SCAR20,		"SCAR-20" },
{ (int)ItemDefinitionIndex::WEAPON_SG553,			"SG-556" },
{ (int)ItemDefinitionIndex::WEAPON_SSG08,			"Scout" },
{ (int)ItemDefinitionIndex::WEAPON_TEC9,			"Tec-9" },
{ (int)ItemDefinitionIndex::WEAPON_UMP45,			"UMP-45" },
{ (int)ItemDefinitionIndex::WEAPON_USPS,	"USP-s" },
{ (int)ItemDefinitionIndex::WEAPON_XM1014, "XM1014" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_BAYONET,					"Bayonet Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_FLIP,					"Flip Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_GUT,					"Gut Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_KARAMBIT,					"Karambit Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_M9_BAYONET,					"M9 Bayonet Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_TACTICAL,					"Hunstman Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_FALCHION,					"Falchion Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_SURVIVAL_BOWIE,					"Bowie Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_BUTTERFLY,					"Butterfly Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_PUSH, "Shadow Daggers" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_GYPSY_JACKKNIFE, "Navaja Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_STILETTO, "Stiletto Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_WIDOWMAKER, "Talon Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_URSUS, "Ursos Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_SKELETON, "Skeleton Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_OUTDOOR, "Nomad Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_CANIS, "Survival Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_CORD, "Paracord Knife" },
{ (int)ItemDefinitionIndex::WEAPON_KNIFE_CSS,"Classic knife"}
};
extern const std::vector<std::pair<int, const char*>> guns;
const std::vector<std::pair<int, const char*>> famas_skins =
{
    { 0, "NONE"},
{604, "Roll Cage" },
{626, "Mecha Industries" },
{529, "valence" },
{492, "Surivor Z" },
{659, "Macabre" },
    {723, "Eye of Athena"},
    {22, "Contrast Spray"},
{47 , "Colony"},
{92 , "Cyanospatter"},
{429 , "Djinn"},
{154 , "Afterimage"},
{178 , "Doomkitty"},
{194 , "Spitfire"},
{244 , "Teardown"},
{218 , "Hexane"},
{260 , "Pulse"},
{288 , "Sergeant"},
{371 , "Styx"},
{477 ," Neural Net"}
};
extern const std::vector<std::pair<int, const char*>> famas_skins;
const std::vector<std::pair<int, const char*>> mag7_skins =
{
    { 0, "NONE" },
    { 462 , "Counter Terrace" },
{ 34 , "Metallic DDPAT" },
{ 32 , "Silver"	},
{ 100 , "Storm" },
{ 39 , "Bulldozer" },
{ 431 , "Heat" },
{ 99 ,"Sand Dune" },
{ 171 , "Irradiated Alert" },
{ 177 , "Memento" },
{ 198 , "Hazard" },
{ 291 , "Heaven Guard" },
{ 385 , "Firestarter" },
{ 473 , "Seabird" },
    {948,"Justice"}
};
extern const std::vector<std::pair<int, const char*>> mag7_skins;
const std::vector<std::pair<int, const char*>> g3sg1_skins =
{
    { 0, "NONE" },
{806, "Scavenger" },
{511, "The Executioner" },
{ 493, "Flux" },
{628, "Stinger" },
{545, "Orange Crash" },
{606, "Ventilator" },
{677, "Hunter" },
    {712, "High Seas"},
    { 8 , "Desert Storm" },
{ 6 , "Arctic Camo" },
{ 27 , "Bone Mask" },
{ 46 , "Contractor" },
{ 72 , "Safari Mesh" },
{ 74 , "Polar Camo"},
{ 147 , "Jungle Dashed" },
{ 235 , "VariCamo" },
{ 170 , "Predator" },
{ 195 , "Demeter" },
{ 229 , "Azure Zebra" },
{ 294 , "Green Apple" },
{ 465 , "Orange Kimono" },
 {464 , "Neon Kimono"},
{ 382 , "Murky" },
{ 438 , "Chronos" }
};
extern const std::vector<std::pair<int, const char*>> g3sg1_skins;
const std::vector<std::pair<int, const char*>> m4a1_skins =
{
    { 0, "NONE" },
{ 844, "Emperor" },
{ 811, "Magnesium" },
{588, "Desolate Space" },
    { 8 , "Desert Storm" },
{ 101 , "Tornado" },
{ 5 , "Forest DDPAT" },
{ 167 , "Radiation Hazard" },
{ 164 , "Modern Hunter" },
{ 16 , "Jungle Tiger" },
{ 17 , "Urban DDPAT" },
{ 155 , "Bullet Rain" },
{ 170 , "Predator" },
{ 176 , "Faded Zebra" },
{ 187 , "Zirka" },
{ 255 , "Asiimov" },
{ 309 , "Howl" },
{ 215 , "X - Ray" },
{ 336 , "Desert - Strike" },
{ 384 , "Griffin" },
{ 471 , "Daybreak" },
{ 449 , "Poseidon" },
{ 480 , "Evil Daimyo" }
};
extern const std::vector<std::pair<int, const char*>> m4a1_skins;
const std::vector<std::pair<int, const char*>> knife_skins =
{
    { 0, "NONE" },
{ 1, "Lore" },
{ 2, "Autotronic" },
{ 3, "Black Laminate" },
{582, "Freehand"},
{578, "Bright Water"},
{569, "Gamma Doppler (Phase 1)"},
{570, "Gamma Doppler (Phase 2)"},
{571, "Gamma Doppler (Phase 3)"},
{572, "Gamma Doppler (Phase 4)"},
{568, "Gamma Doppler (Emerald)"},
{418, "Doppler (Phase 1)"},
{618, "Doppler (Phase 2)"},
{420, "Doppler (Phase 3)"},
{421, "Doppler (Phase 4)"},
{415, "Doppler (Ruby)"},
{619, "Doppler (Saphire)"},
{617, "Doppler (Black Pearl)"},
    { 5 , "Forest DDPAT" },
{ 418 , "Doppler" },
{ 12 , "Crimson Web" },
{ 59 , "Slaughter" },
{ 27 , "Bone Mask" },
{ 38 , "Fade" },
{ 40 , "Night"},
{ 42 , "Blue Steel" },
{ 43 , "Stained "},
{ 44 , "Case Hardened"},
{ 72 , "Safari Mesh" },
{ 77 , "Boreal Forest "},
{ 98 , "Ultraviolet "},
{ 143 , "Urban Masked" },
{ 410 , "Damascus Steel" },
{ 175 , "Scorched" },
{ 409 , "Tiger Tooth" },
{ 414 , "Rust Coat" },
{ 413 , "Marble Fade"},
{ 323 , "Rust Coat" }
};
extern const std::vector<std::pair<int, const char*>> knife_skins;
const std::vector<std::pair<int, const char*>> deagle_skins =
{
    { 0, "NONE" },
{ 841, "Light Rail" },
{805, "Mecha Industries" },
{527, "Kumicho Dragon" },
{603, "Directive" },
{645, "Oxide Blaze" },
{509, "Corinthian" },
{17, "Urban DDPAT" },

    {711, "Code Red"},
    { 37 , "Blaze" },
{ 347 , "Pilot" },
{ 468 , "Midnight Storm" },
{ 469 , "Sunset Storm" },
{ 5 , "Forest DDPAT" },
{ 12 , "Crimson Web" },
{ 17 , "Urban DDPAT" },
{ 40 , "Night"},
{ 61 , "Hypnotic" },
{ 90 , "Mudder" },
{ 235 , "VariCamo" },
{ 185 , "Golden Koi" },
{ 248 , "Red Quartz" },
{ 231 , "Cobalt Disruption" },
{ 232 , "Crimson Web" },
{ 237 , "Urban Rubble" },
{ 397 , "Naga" },
{ 328 , "Hand Cannon" },
{ 273 , "Heirloom" },
{ 296 , "Meteorite" },
{ 351 , "Conspiracy" },
{ 425 , "Bronze Deco" },
{ 470 , "Sunset Storm" },
{945,"Blue Ply"}
};
extern const std::vector<std::pair<int, const char*>> deagle_skins;
const std::vector<std::pair<int, const char*>> awp_skins =
{
    { 0, "NONE" },
{ 838, "Atheris" },
{803, "Neo-Noir" },
{ 662, "Oni Tajii" },
{691, "Mortis" },
{640, "Fever Dream" },
{525, "Elite Build" },
{584, "Phobos" },
{788, "Acheron" },
    {718, "Paw" },
    { 174 , "BOOM" },
{ 344 , "Dragon Lore" },
{ 5 , "Forest DDPAT" },
{ 84 , "Pink DDPAT" },
{ 30 , "Snake Camo" },
{ 51 , "Lightning Strike" },
{ 72 , "Safari Mesh" },
{ 181 , "Corticera" },
{ 259 , "Redline" },
{ 395 , "Man , o ,war" },
{ 212 , "Graphite" },
{ 227 , "Electric Hive" },
{ 251 , "Pit Viper" },
{ 279 , "Asiimov" },
{ 424 , "Worm God" },
{ 446 , "Medusa" },
{ 451 , "Sun in Leoa" },
{ 475 , "Hyper Beast" },
{736 ,"The prince"},
{756,"Gungnir"},
    {943,"Capilary"}
};
extern const std::vector<std::pair<int, const char*>> awp_skins;
const std::vector<std::pair<int, const char*>> m249_skins =
{
    { 0, "NONE" },
    { 5 , "Forest DDPAT" },
{ 22 , "Contrast Spray" },
{ 75 , "Blizzard Marbleized" },
{ 202 , "Jungle DDPAT" },
{ 243 , "Gator Mesh" },
{ 266 , "Magma" },
{ 401 , "System Lock" },
{ 452 , "Shipping Forecast" },
{ 472 , "Impact Drill" },
};
extern const std::vector<std::pair<int, const char*>> m249_skins;
const std::vector<std::pair<int, const char*>> cz_skins =
{
    { 0, "NONE" },
{643, "Xiangliu" },
{543, "Red Astor" },
{687, "Tacticat" },
{622, "Polymer" },
{602, "Imprint" },
{12, "Crimson Web" },
    {709, "Eco" },
    { 435 , "Pole Position" },
{ 12 , "Crimson Web"},
{ 254 , "Nitro" },
{ 218 , "Hexane" },
{ 268 , "Tread Plate" },
{ 269 , "The Fuschia Is Now" },
{ 270 , "Victoria" },
{ 297 , "Tuxedo" },
{ 298 , "Army Sheen" },
{ 315 , "Poison Dart" },
{ 322 , "Nitro" },
{ 325 , "Chalice" },
{ 334 , "Twist" },
{ 350 , "Tigris" },
{ 366 , "Green Plaid" },
{ 453 , "Emerald" },
{ 476 , "Yellow Jacket" },
{944,"Distressed "}
};
extern const std::vector<std::pair<int, const char*>> cz_skins;
const std::vector<std::pair<int, const char*>> aug_skins =
{
    { 0, "NONE" },
{ 845, "Momentum" },
{690, "Stymphalian" },
{541, "Fleet Flock" },
{601, "Syd Mead" },
{583, "Aristocrat" },
{674, "Triqua" },
{708, "Amber Slipstream" },
{507, "Ricochet" },
{779, "Random Acess" },
{794, "Sweeper" },
    { 708, "Amber Slipstream" },
    { 73 , "Wings" },
{ 10 , "Copperhead" },
{ 9 , "Bengal Tiger" },
{ 28 , "Anodized Navy" },
{ 167 , "Radiation Hazard" },
{ 110 , "Condemned" },
{ 33 , "Hot Rod" },
{ 100 , "Storm" },
{ 46 , "Contractor" },
{ 47 , "Colony" },
{ 197 , "Anodized Navy" },
{ 280 , "Chameleon" },
{ 305 , "Torque" },
{ 375 , "Radiation Hazard" },
{ 442 , "Asterion" },
{ 444 , "Daedalus" },
{ 455 , "Akihabara Accept" },
{942,"Tom Cat"}
};
extern const std::vector<std::pair<int, const char*>> aug_skins;
const std::vector<std::pair<int, const char*>> ump_skins =
{
    { 0, "NONE" },
{ 851, "Moonrise" },
{802, "Momentum" },
{ 556, "Primal Saber" },
{ 704, "Artic Wolf" },
{688, "Expsure" },
{652, "Scaffold" },
{ 672, "Metal Flowers" },
{ 615, "Briefing" },
{ 441, "Minotauros Labyrinth" },
{90, "Mudder" },
{778, "Facility Dark" },
    { 37 , "Blaze" },
{ 5 , "Forest DDPAT" },
{ 15 , "Gunsmoke" },
{ 17 , "Urban DDPAT" },
{ 436 , "Grand Prix" },
{ 70 , "Carbon Fiber" },
{ 93 , "Caramel" },
{ 169 , "Fallout Warning" },
{ 175 , "Scorched" },
{ 193 , "Bone Pile" },
{ 392 , "Delusion" },
{ 281 , "Corporal" },
{ 333 , "Indigo" },
{ 362 , "Labyrinth" },
{ 488 , "Riot"}
};
extern const std::vector<std::pair<int, const char*>> ump_skins;
const std::vector<std::pair<int, const char*>> mac10_skins =
{
    { 0, "NONE" },
{840, "Whitefish" },
{812, "Pipe Down" },
{651, "Last Dive" },
{682, "Oceanic" },
{ 534, "Lapis Gator" },
{665, "Aloha" },
{589, "Carnivore" },
{498, "Rangeen" },
{748, "Calf Skin" },
{ 17, "Ureban DDPAT" },
    { 101 , "Tornado" },
{ 3 , "Candy Apple" },
{ 32 , "Silver" },
{ 5 , "Forest DDPAT" },
{ 17 , "Urban DDPAT" },
{ 38 , "Fade" },
{ 433 , "Neon Rider" },
{ 98 , "Ultraviolet" },
{ 157 , "Palm" },
{ 188 , "Graven" },
{ 337 , "Tatter" },
{ 246 , "Amber Fade" },
{ 284 , "Heat" },
{ 310 , "Curse" },
{ 333 , "Indigo" },
{ 343 , "Commuter" },
{ 372 , "Nuclear Garden"},
{ 402 , "Malachite" },
    {947,"Disco Tech"}
};
extern const std::vector<std::pair<int, const char*>> mac10_skins;
const std::vector<std::pair<int, const char*>> tec9_skins =
{
    { 0, "NONE" },
{ 839, "Bamboozle" },
{816, "Fubar" },
    {722, "Snek-9" },
{ 614, "Fuel Injector" },
{ 791, "Remote Control" },
{555, "Re-Entry"},
{520, "Avalanche" },
{599, "Ice Cap" },
{ 671, "Cut Out" },
{ 539, "Jambiya" },
{ 684, "Cracked Opal" },
{ 235, "VariCamo" },
{ 101 , "Tornado" },
{ 2 , "Groundwater" },
{ 5 , "Forest DDPAT" },
{ 463 , "Terrace" },
{ 17 , "Urban DDPAT" },
{ 36 , "Ossified" },
{ 439 , "Hades" },
{ 159 , "Brass" },
{ 168 , "Nuclear Threat" },
{ 235 , "VariCamo" },
{ 179 , "Nuclear Threat" },
{ 248 , "Red Quartz" },
{ 206 , "Tornado" },
{ 216 , "Blue Titanium" },
{ 242 , "Army Mesh" },
{ 272 , "Titanium Bit" },
{ 289 , "Sandstorm" },
{ 303 , "Isaac" },
{ 374 , "Toxic" },
{ 459 , "Bamboo Forest" }
};
extern const std::vector<std::pair<int, const char*>> tec9_skins;
const std::vector<std::pair<int, const char*>> sg556_skins =
{
    { 0, "NONE" },
{815, "Danger Close" },
{750, "Integrale" },
{686, "Phantom" },
{613, "Triach" },
{519, "Tiger Moth" },
{702, "Aloha" },
{553, "Atlas" },
{598, "Arial" },
    { 101 , "Tornado" },
{ 28 , "Anodized Navy" },
{ 22 , "Contrast Spray" },
{ 27 , "Bone Mask" },
{ 39 , "Bulldozer" },
{ 98 , "Ultraviolet" },
{ 136 , "Waves Perforated" },
{ 410 , "Damascus Steel" },
{ 169 , "Fallout Warning" },
{ 186 , "Wave Spray" },
{ 243 , "Gator Mesh" },
{ 247 , "Damascus Steel" },
{ 287 , "Pulse" },
{ 298 , "Army Sheen" },
{ 363 , "Traveler" },
{ 378 , "Fallout Warning" },
{ 487 , "Cyrex" },
    {955,"Darkwing"}
};
extern const std::vector<std::pair<int, const char*>> sg556_skins;
const std::vector<std::pair<int, const char*>> p2000_skins =
{
    { 0, "NONE" },
{ 591, "Imperial Dragon" },
{ 667, "Woodsman" },
{ 700, "Urban Hazard" },
{ 550, "Oceanic" },
{ 635, "Turf" },
{ 515, "Imperial" },
    { 104 , "Grassland Leaves" },
{ 32 , "Silver" },
{ 21 , "Granite Marbleized" },
{ 25 , "Forest Leaves" },
{ 36 , "Ossified" },
{ 485 , "Handgun" },
{ 38 , "Fade" },
{ 71 , "Scorpion" },
{ 95 , "Grassland" },
{ 184 , "Corticera" },
{ 211 , "Ocean Foam" },
{ 338 , "Pulse" },
{ 246 , "Amber Fade" },
{ 275 , "Red FragCam" },
{ 327 , "Chainmail" },
{ 346 , "Coach Class" },
{ 357 , "Ivory" },
{ 389 , "Fire Elemental" },
{ 442 , "Asterion" },
{ 443 , "Pathfinder" },
{951,"Acid Etched"}
};
extern const std::vector<std::pair<int, const char*>> p2000_skins;
const std::vector<std::pair<int, const char*>> sawedoff_skins =
{
    { 0, "NONE" },
{814, "Black Sand" },
    { 345 , "First Class" },
{ 5 , "Forest DDPAT" },
{ 22 , "Contrast Spray" },
{ 30 , "Snake Camo" },
{ 83 , "Orange DDPAT" },
{ 38 , "Fade" },
{ 41 , "Copper" },
{ 434 , "Origami" },
{ 119 , "Sage Spray" },
{ 235 , "VariCamo" },
{ 171 , "Irradiated Alert" },
{ 204 , "Mosaico" },
{ 405 , "Serenity" },
{ 246 , "Amber Fade" },
{ 250 , "Full Stop" },
{ 390 , "Highwayman" },
{ 256 , "The Kraken" },
{ 323 , "Rust Coat" },
{ 458 , "Bamboo Shadow" },
{ 459 , "Bamboo Forest" },
{953,"Apocalypto"}
};
extern const std::vector<std::pair<int, const char*>> sawedoff_skins;
const std::vector<std::pair<int, const char*>> glock_skins =
{
    { 0, "NONE" },
{808, "Oxide Blaze" },
{586, "Wasteland Rebel" },
{694, "Moonrise" },
{607, "Weasel" },
{532, "Royal Legion" },
{789, "Nuclear Garden" },
{680, "Off World" },
{623, "Ironwork" },
{495, "Wraiths" },
{799, "High Beam" },
    {713, "Warhawk"},
    { 2 , "Groundwater" },
{ 3 , "Candy Apple" },
{ 38 , "Fade" },
{ 40 , "Night" },
{ 48 , "Dragon Tattoo" },
{ 437 , "Twilight Galaxy" },
{ 99 , "Sand Dune" },
{ 159 , "Brass" },
{ 399 , "Catacombs" },
{ 208 , "Sand Dune" },
{ 230 , "Steel Disruption" },
{ 278 , "Blue Fissure" },
{ 293 , "Death Rattle" },
{ 353 , "Water Elemental" },
{ 367 , "Reactor" },
{ 381 , "Grinder" },
{ 479 , "Bunsen Burner" },
    {957,"Bullet Queen"}
};
extern const std::vector<std::pair<int, const char*>> glock_skins;
const std::vector<std::pair<int, const char*>> galil_skins =
{
    { 0, "NONE" },
{842, "Akoben" },
{807, "Signal" },
{398, "Chatterbox" },
{661, "Sugar Rush" },
{546, "Firefight" },
{647, "Crimson Tsunami" },
{494, "Stone Cold" },
{629, "Black Sand" },
{790, "Cold Fusion" },
{241, "Hunting Blind" },
    { 5 , "Forest DDPAT" },
{ 22 , "Contrast Spray" },
{ 83 , "Orange DDPAT" },
{ 428 , "Eco" },
{ 76 , "Winter Forest" },
{ 119 , "Sage Spray" },
{ 235 , "VariCamo" },
{ 192 , "Shattered" },
{ 308 , "Kami" },
{ 216 , "Blue Titanium" },
{ 237 , "Urban Rubble" },
{ 241 , "Hunting Blind" },
{ 264 , "Sandstorm" },
{ 297 , "Tuxedo" },
{ 379 , "Cerberus" },
{ 460 , "Aqua Terrace" },
{ 478 , "Rocket Pop" }
};
extern const std::vector<std::pair<int, const char*>> galil_skins;
const std::vector<std::pair<int, const char*>> mp7_skins =
{
    { 0, "NONE" },
{857, "Mischief" },
    {719, "Powercore"},
{696, "Bloodsport" },
{500, "Special Delivery" },
{536, "Empire" },
{649, "Akoben" },
{ 752, "Fade" },
{ 213, "Ocean Foam" },
{ 627, "Cirrus" },
{ 782, "Motherboard" },
{ 141, "Orange Peel" },
    { 2 , "Groundwater" },
{ 102 , "Whiteout" },
{ 5 , "Forest DDPAT" },
{ 28 , "Anodized Navy" },
{ 11 , "Skulls" },
{ 15 , "Gunsmoke" },
{ 22 , "Contrast Spray" },
{ 27 , "Bone Mask" },
{ 36 , "Ossified" },
{ 141 , "Orange Peel" },
{ 235 , "VariCamo" },
{ 245 , "Army Recon" },
{ 209 , "Groundwater" },
{ 213 , "Ocean Foam" },
{ 250 , "Full Stop" },
{ 354 , "Urban Hazard" },
{ 365 , "Olive Plaid" },
{ 423 , "Armor Core" },
{ 442 , "Asterion" },
{ 481 , "Nemesis" }
};
extern const std::vector<std::pair<int, const char*>> mp7_skins;
const std::vector<std::pair<int, const char*>> p250_skins =
{
    { 0, "NONE" },
{ 848, "Verdigris" },
{813, "Nevermore" },
{678, "See Ya Later" },
{551, "Asiimov" },
{258, "Mehndi" },
{501, "Wingshot" },
{668, "Red Rock" },
{749, "Vino Primo" },
{650, "Ripple" },
{592, "Iron Clad" },
{786, "Exchanger" },
{777, "Facility Draft" },
    { 102 , "Whiteout" },
{ 34 , "Metallic DDPAT" },
{ 162 , "Splash" },
{ 15 , "Gunsmoke" },
{ 164 , "Modern Hunter" },
{ 27 , "Bone Mask" },
{ 77 , "Boreal Forest" },
{ 99 , "Sand Dune" },
{ 168 , "Nuclear Threat" },
{ 258 , "Mehndi" },
{ 207 , "Facets" },
{ 219 , "Hive" },
{ 404 , "Muertos" },
{ 230 , "Steel Disruption" },
{ 271 , "Undertow" },
{ 295 , "Franklin" },
{ 464 , "Neon Kimono" },
{ 358 , "Supernova" },
{ 373 , "Contamination" },
{ 388 , "Cartel" },
{ 426 , "Valence" },
{ 466 , "Crimson Kimono" },
{ 467 , "Mint Kimono" }
};
extern const std::vector<std::pair<int, const char*>> p250_skins;
const std::vector<std::pair<int, const char*>> MP5 =
{
    {0, "NONE" },
{ 847, "Gauss" },
    {810, "Phosphor" },
    { 781, "Co-Processor" },
{ 753, "Dirt Drop" },
{494,"Desert Strike"}
};
extern const std::vector<std::pair<int, const char*>> MP5;
const std::vector<std::pair<int, const char*>> five7_skins =
{
    { 0, "NONE" },
{ 837, "Angry Bob" },
{ 660, "Hyper Beast" },
{ 510, "Retrobution" },
{ 530, "Triumvirate" },
{ 605, "Scumbria" },
{ 646, "Capillary" },
{ 693, "Flame Test" },
{ 585, "Violent Daimyo" },
{ 784, "Coolant" },
    { 3 , "Candy Apple" },
{ 27 , "Bone Mask" },
{ 44 , "Case Hardened" },
{ 46 , "Contractor" },
{ 78 , "Forest Night" },
{ 141 , "Orange Peel" },
{ 151 , "Jungle" },
{ 254 , "Nitro" },
{ 248 , "Red Quartz" },
{ 210 , "Anodized Gunmetal" },
{ 223 , "Nightshade" },
{ 252 , "Silver Quartz "},
{ 265 , "Kami" },
{ 274 , "Copper Galaxy" },
{ 464 , "Neon Kimono" },
{ 352 , "Fowl Play" },
{ 377 , "Hot Shot" },
{ 387 , "Urban Hazard" },
{ 427 , "Monkey Business" }
};
extern const std::vector<std::pair<int, const char*>> five7_skins;
const std::vector<std::pair<int, const char*>> nova_skins =
{
    { 0, "NONE" },
{809, "Wood Fired" },
    {716, "Toy Soldier"},
    { 3 , "Candy Apple" },
{ 166 , "Blaze Orange" },
{ 164 , "Modern Hunter" },
{ 25 , "Forest Leaves" },
{ 62 , "Bloomstick" },
{ 99 , "Sand Dune" },
{ 107 , "Polar Mesh" },
{ 158 , "Walnut" },
{ 170 , "Predator" },
{ 191 , "Tempest" },
{ 214 , "Graphite" },
{ 225 , "Ghost Camo" },
{ 263 , "Rising Skull" },
{ 286 , "Antique" },
{ 294 , "Green Apple" },
{ 299 , "Caged Steel" },
{ 356 , "Koi" },
{ 450 , "Moon in Libra" },
{ 484 , "Ranger" }
};
extern const std::vector<std::pair<int, const char*>> nova_skins;
const std::vector<std::pair<int, const char*>> negev_skins =
{
    { 0, "NONE" },
    { 28 , "Anodized Navy" },
{ 432 ," Man -o- war" },
{ 157 , "Palm" },
{ 235 , "VariCamo" },
{ 201 , "Palm" },
{ 240 , "CaliCamo" },
{ 285 , "Terrain" },
{ 298 , "Army Sheen" },
{ 317 , "Bratatat" },
{ 355 , "Desert - Strike" },
{ 369 , "Nuclear Waste" },
{ 483 , "Loudmouth" },
 {950,"Prototype"}
};
extern const std::vector<std::pair<int, const char*>> negev_skins;
const std::vector<std::pair<int, const char*>> p90_skins =
{
    { 0, "NONE" },
{ 849, "Off World" },
    { 636, "Shallow Grave"},
{516, "Shapewood" },
{669, "Death Grip" },
{593, "Chopper" },
{611, "Grim" },
{776, "Facility Negative" },
{111, "Glaciar Mesh" },
{175, "Scorched" },
    {717, "Traction"},
    { 342 , "Leather" },
{ 20 , "Virus" },
{ 22 , "Contrast Spray" },
{ 100 , "Storm" },
{ 67 , "Cold Blooded" },
{ 111 , "Glacier Mesh" },
{ 124 , "Sand Spray" },
{ 156 , "Death by Kitty" },
{ 234 , "Ash Wood" },
{ 169 , "Fallout Warning" },
{ 175 , "Scorched" },
{ 182 , "Emerald Dragon" },
{ 244 , "Teardown" },
{ 228 , "Blind Spot" },
{ 283 , "Trigon" },
{ 311 , "Desert Warfare" },
{ 335 , "Module" },
{ 359 , "Asiimov" },
{ 486 , "Elite Build" }
};
extern const std::vector<std::pair<int, const char*>> p90_skins;
const std::vector<std::pair<int, const char*>> scar_skins =
{
    { 0, "NONE" },
{597, "Bloodsport" },
{612, "Powercore" },
{685, "Jungle Slipstream" },
{642, "Blueprint" },
{502, "Green Marine" },
{518, "Outbrake" },
    { 12 , "Crimson Web" },
{ 165 , "Splash Jam" },
{ 100 , "Storm" },
{ 46 , "Contractor" },
{ 70 , "Carbon Fiber" },
{ 116 , "Sand Mesh" },
{ 157 , "Palm" },
{ 196 , "Emerald" },
{ 232 , "Crimson Web" },
{ 391 , "Cardiac" },
{ 298 , "Army Sheen" },
{ 312 , "Cyrex" },
{ 406 , "Grotto" },
{ 453 , "Emerald" },
    {954,"Enforcer"}
};
extern const std::vector<std::pair<int, const char*>> scar_skins;
const std::vector<std::pair<int, const char*>> mp9_skins =
{
    { 0, "NONE" },
{804, "Modest Thread" },
{609, "Airlock" },
{697, "Black Sand" },
{630, "Sand Scale" },
{549, "Bioleak" },
{366, "Green Palid" },
{755, "Slide" },
    {715, "Capillary"},
    { 482 , "Ruby Poison Dart" },
{ 27 , "Bone Mask" },
{ 33 , "Hot Rod" },
{ 100 , "Storm" },
{ 39 , "Bulldozer" },
{ 61 , "Hypnotic" },
{ 148 , "Sand Dashed" },
{ 141 , "Orange Peel" },
{ 199 , "Dry Season" },
{ 329 , "Dark Age" },
{ 262 , "Rose Iron" },
{ 366 , "Green Plaid" },
{ 368 , "Setting Sun" },
{ 386 , "Dart" },
{ 403 , "Deadly Poison" },
{ 448 , "Pandora's Box" }
};
extern const std::vector<std::pair<int, const char*>> mp9_skins;
const std::vector<std::pair<int, const char*>> ak47_skins =
{
    { 0, "NONE" },
{ 837, "Uncharted" },
{801, "Asiimov" },
{675, "The Empress" },
{639, "Bloodsport" },
{600, "Neon Revolution" },
{524, "Fuel Injector" },
{506, "Point Disarray" },
{490, "Frontside-Misty" },
{656, "Orbit Mk01" },
{795, "Safety Net" },
{707, "Neon Rider"},
{ 341 , "First Class" },
{ 14 , "Red Laminate" },
{ 22 , "Contrast Spray" },
{ 44 , "Case Hardened" },
{ 72 , "Safari Mesh" },
{ 122 , "Jungle Spray" },
{ 170 , "Predator" },
{ 172 , "Black Laminate" },
{ 180 , "Fire Serpent" },
{ 394 , "Cartel" },
{ 300 , "Emerald Pinstripe" },
{ 226 , "Blue Laminate" },
{ 282 , "Redline"},
{ 302 , "Vulcan" },
{ 316 , "Jaguar" },
{ 340 , "Jet Set" },
{ 380 , "Wasteland Rebel" },
{ 422 , "Elite Build" },
{ 456 , "Hydroponic" },
{ 474 , "Aquamarine Revenge" },
{724 ,"Wild lotus"},
{941,"Phantom Disruptor"}
};
extern const std::vector<std::pair<int, const char*>> ak47_skins;
const std::vector<std::pair<int, const char*>> m4a1s_skins =
{
    { 0, "NONE" },
    {695, "Neo-Noir" },
{632, "Buzz Kill" },
{512, "Royal Pladin" },
{533, "The Battlestar" },
{664, "Hellfire" },
{ 400, "Dragon King" },
{793, "Converter" },
{17, "Urban DDPAT" },
{780, "Mainframe" },
{ 587, "Mecha Industries" },
{ 548, "Chantico's Fire" },
{ 497, "Golden Coild" },
{ 644, "Decimator" },
{ 681, "Leaded Glass" },
{ 792, "Control Panel" },
{631, "Flashback" },
{663, "Briefing" },
    {714, "Nightmare"},
    { 33 , "Hot Rod" },
{ 60 , "Dark Water" },
{ 430 , "Hyper Beast" },
{ 77 , "Boreal Forest" },
{ 235 , "VariCamo" },
{ 254 , "Nitro" },
{ 189 , "Bright Water" },
{ 301 , "Atomic Alloy" },
{ 217 , "Blood Tiger" },
{ 257 , "Guardian" },
{ 321 , "Master Piece" },
{ 326 , "Knight" },
{ 360 , "Cyrex" },
{ 383 , "Basilisk" },
{ 440 , "Icarus Fell" },
{ 445 , "Hot Rod" },
    {946,"Player Two"}
};
extern const std::vector<std::pair<int, const char*>> m4a1s_skins;
const std::vector<std::pair<int, const char*>> elite_skins =
{
    { 0, "NONE" },
{658, "Cobra Strike" },
{625, "Royal Consorts" },
{491, "Dualing Dragons" },
{747, "Twin Turbo" },
{544, "Ventilators" },
{528, "Cartel" },
{330, "Brial" },
    {730, "Shred"},
    { 28 , "Anodized Navy" },
{ 36 , "Ossified" },
{ 43 , "Stained" },
{ 46 , "Contractor" },
{ 47 , "Colony" },
{ 153 , "Demolition" },
{ 190 , "Black Limba" },
{ 248 , "Red Quartz" },
{ 249 , "Cobalt Quartz" },
{ 220 , "Hemoglobin" },
{ 396 , "Urban Shock" },
{ 261 , "Marina" },
{ 276 , "Panther" },
{ 307 , "Retribution" },
{ 330 , "Briar" },
{ 447 , "Duelist" },
{ 450 , "Moon in Libra" }
};
extern const std::vector<std::pair<int, const char*>> elite_skins;
const std::vector<std::pair<int, const char*>> bizon_skins =
{
    { 0, "NONE" },
{542, "Judgement of Anubis" },
{ 676, "High Roller" },
{508, "Fuel Rod" },
{13, "Blue Streak" },
{641, "Jungle Slipstream" },
{692, "Night Riot" },
{526, "Photic Zone" },
{224, "Water Sigil" },
{594, "Harvester" },
{3, "Candy Apple" },
    { 13 , "Blue Streak" },
{ 164 , "Modern Hunter" },
{ 25 , "Forest Leaves" },
{ 27 , "Bone Mask" },
{ 70 , "Carbon Fiber" },
{ 148 , "Sand Dashed" },
{ 149 , "Urban Dashed" },
{ 159 , "Brass" },
{ 235 , "VariCamo" },
{ 171 , "Irradiated Alert" },
{ 203 , "Rust Coat" },
{ 224 , "Water Sigil" },
{ 236 , "Night Ops" },
{ 267 , "Cobalt Halftone" },
{ 306 , "Antique" },
{ 323 , "Rust Coat" },
{ 349 , "Osiris" },
{ 376 , "Chemical Green" },
{ 457 , "Bamboo Print" },
{ 459 , "Bamboo Forest" }
};
extern const std::vector<std::pair<int, const char*>> bizon_skins;
const std::vector<std::pair<int, const char*>> xm1014_skins =
{
    { 0, "NONE" },
    { 166 , "Blaze Orange" },
{ 238 , "VariCamo Blue" },
{ 27 , "Bone Mask" },
{ 42 , "Blue Steel" },
{ 96 , "Blue Spruce" },
{ 95 , "Grassland" },
{ 135 , "Urban Perforated" },
{ 151 , "Jungle" },
{ 235 , "VariCamo" },
{ 169 , "Fallout Warning" },
{ 205 , "Jungle" },
{ 240 , "CaliCamo" },
{ 251 , "Pit Viper" },
{ 393 , "Tranquility" },
{ 320 , "Red Python" },
{ 314 , "Heaven Guard" },
{ 348 , "Red Leather" },
{ 370 , "Bone Machine" },
{ 407 , "Quicksilver" }
};
extern const std::vector<std::pair<int, const char*>> xm1014_skins;
const std::vector<std::pair<int, const char*>> revolver_skins =
{
    {0, "NONE" },
{ 843,  "Skull Crusher" },
    {522, "Fade" },
{ 683, "Llama Cannon"},
{ 523, "Amber Fade" },
{ 595, "Reboot" },
{ 721, "Survivalist" },
{ 701, "Grip" },
{ 12, "Crimson Web" },
{ 798, "Nitro" },
{ 27, "Bone Mask" },
{952,"Bone Forged"}
};
extern const std::vector<std::pair<int, const char*>> revolver_skins;
const std::vector<std::pair<int, const char*>> usp_skins =
{
    { 0, "NONE" },
{817, "Flashback" },
{653, "Neo-Noir" },
{504, "Kill Confirmed" },
{705, "Cortex" },
{637, "Cyrex" },
{796, "Check Engine" },
{657, "Blue Print" },
{540, "Lead Conduit" },
    { 25 , "Forest Leaves" },
{ 60 , "Dark Water" },
{ 235 , "VariCamo" },
{ 183 , "Overgrowth" },
{ 339 , "Caiman" },
{ 217 , "Blood Tiger" },
{ 221 , "Serum" },
{ 236 , "Night Ops" },
{ 277 , "Stainless" },
{ 290 , "Guardian" },
{ 313 , "Orion" },
{ 318 , "Road Rash" },
{ 332 , "Royal Blue" },
{ 364 , "Business Class" },
{ 454 , "Para Green" },
{ 489 , "Torque" }
};
extern const std::vector<std::pair<int, const char*>> usp_skins;
const std::vector<std::pair<int, const char*>> scout_skins =
{
    { 0, "NONE" },
{624, "Dragon Fire" },
{503, "Big Iron" },
{554, "Ghost Crusader" },
{670, "Deaths Head" },
{538, "Necropos"},
{751, "Hand Brake" },

    { 26 , "Lichen Dashed" },
{ 38 , "Fade" },
{ 60 , "Dark Water" },
{ 96 , "Blue Spruce" },
{ 99 , "Sand Dune" },
{ 157 , "Palm" },
{ 200 , "Mayan Dreams" },
{ 222 , "Blood in the Water" },
{ 233 , "Tropical Storm" },
{ 253 , "Acid Fade" },
{ 304 , "Slashed" },
{ 319 , "Detour" },
{ 361 , "Abyss" },
    {956,"Fever dream"}
};
extern const std::vector<std::pair<int, const char*>> scout_skins;

const std::vector<std::pair<int, const char*>> null_skins2 =
{

};
extern const std::vector<std::pair<int, const char*>> null_skins2;
