#pragma once

//HitGroups
#define HITGROUP_GENERIC  0
#define HITGROUP_HEAD     1
#define HITGROUP_CHEST    2
#define HITGROUP_STOMACH  3
#define HITGROUP_LEFTARM  4    
#define HITGROUP_RIGHTARM 5
#define HITGROUP_LEFTLEG  6
#define HITGROUP_RIGHTLEG 7
#define HITGROUP_GEAR    10


//HitBoxes
#define HITBOX_HEAD   0
#define HITBOX_NECK   1
#define HITBOX_PELVIS 2
#define HITBOX_BELLY  3
#define HITBOX_THORAX 4
#define HITBOX_LOWER_CHEST 5
#define HITBOX_UPPER_CHEST 6
#define HITBOX_RIGHT_THIGH 7
#define HITBOX_LEFT_THIGH  8
#define HITBOX_RIGHT_CALF  9
#define HITBOX_LEFT_CALF  10
#define HITBOX_RIGHT_FOOT 11
#define HITBOX_LEFT_FOOT  12
#define HITBOX_RIGHT_HAND 13
#define HITBOX_LEFT_HAND  14
#define HITBOX_RIGHT_UPPER_ARM 15
#define HITBOX_RIGHT_FOREARM   16
#define HITBOX_LEFT_UPPER_ARM  17
#define HITBOX_LEFT_FOREARM    18
#define HITBOX_MAX 19